server:
  port: 8080

spring:
  application:
    name: sleep-spring

  datasource:
    url: jdbc:postgresql://localhost:5432/sleepdb
    username: postgres
    password: ?
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# FastAPI 서버 연결 설정
fastapi:
  base-url: http://127.0.0.1:8000
