server:
  port: 8080

spring:
  application:
    name: sleep-spring

  datasource:
    url: jdbc:postgresql://localhost:5432/sleepdb
    username: postgres
    password: "0411"
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.sleep.model

# FastAPI 서버 연결 설정
fastapi:
  base-url: http://127.0.0.1:8000
